### ISSUE TITLE
listchar colors

### ISSUE THREAD

**Issue by jrock2004** [Rigellute/shades-of-purple.vim#1]
Not sure if blue is the color that is expected for showing tab characters and such?

<img width="723" alt="image" src="https://user-images.githubusercontent.com/655716/57951280-983d1900-78b7-11e9-843e-6926523a444a.png">

**Comment by Rigellute** [comment]
I've just added the correct color for `NonText` items (which I think are what is showing up as blue in your screenshot) 
Commit: https://github.com/Rigellute/shades-of-purple.vim/commit/625b04023edb0dc81126faacdf3f37e4557c6933
