### ISSUE TITLE
Shows ^ characters in airline bar when using split buffers

### ISSUE THREAD

**Issue by aquatix** [Rigellute/shades-of-purple.vim#2]
For example, see https://dl.aquariusoft.org/ss/20190604_shades_of_purple_vim.png

I tested it with and without tmux, the visible characters show up in both cases.

**Comment by aquatix** [comment]
It only shows them on the active buffer (the one with cursor focus). I'm on Ubuntu 18.10 with vim 8.0 patch level 1766. Font is 'Hack Nerd Font Mono'.

The falcon theme, which is also generated by estilo, somehow does not show it like this: https://dl.aquariusoft.org/ss/20190604_falcon_vim.png

**Comment by aquatix** [comment]
Apart from this glitch, I think it would be great to change the colour of the buffer devider from dark on white, to a white or purple foreground for the pipe character, with the same background colour as the line number bar.

**Comment by Rigellute** [comment]
Thanks for this issue, and for the reference to the falcon theme - I will investigate it!
As for your additional issue about the `VertSplit` styling. I have just pushed a fix for it

| Before               | After               |
| -------------------- | ------------------- |
| <img width="221" alt="Screenshot 2019-06-06 at 10 11 30" src="https://user-images.githubusercontent.com/12150276/59021411-a392bd00-8843-11e9-9382-e3fd28f29a2a.png"> |  <img width="221" alt="Screenshot 2019-06-06 at 10 11 43" src="https://user-images.githubusercontent.com/12150276/59021410-a2fa2680-8843-11e9-8fde-4943800749bf.png"> |

**Comment by Rigellute** [comment]
Have fixed the airline status bar issue here https://github.com/Rigellute/shades-of-purple.vim/commit/621ae522a828175cb4e9267d1b64c1c3e1ede925

Let me know if that works for you!

**Comment by aquatix** [comment]
Both changes look great, thanks so much! Love me some neon in my vim :)

What font are you using in this screenshot, it makes the VertSplit pipes look continuous.

**Comment by Rigellute** [comment]
Awesome!

The font I am currently using is `Meslo LG S DZ for Powerline` from [power line fonts](https://github.com/powerline/fonts).

I should add this to the `README`.
