### ISSUE TITLE
Add color for cursorColumn to match cursorLine

### ISSUE THREAD

**Issue by frostspanner** [Rigellute/shades-of-purple.vim#3]
Right now setting cursorColumn does not look great

**Comment by Rigellute** [comment]
Thanks for this.
Have just pushed up a fix adding better highlighting for `CursorColumn`.

<img width="368" alt="Screenshot 2019-06-14 at 09 24 17" src="https://user-images.githubusercontent.com/12150276/59494994-4bcd0500-8e86-11e9-9e0e-e643f05bb308.png">

Let me know what you think!
