### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Almoullim** [Rigellute/shades-of-purple.vim#4]
<img width="663" alt="Screen Shot 2019-08-09 at 4 45 31 AM" src="https://user-images.githubusercontent.com/8402210/62748361-10ebe580-ba61-11e9-91e5-3e131c983fec.png">

**Comment by Rigellute** [comment]
Hmm... sorry to hear this.

Are you using `vim` or `neovim`? Also, are you running inside `tmux`?

What version of `vim/nvim` are you running?

**Comment by Almoullim** [comment]
@Rigellute  Vim with https://github.com/amix/vimrc
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 19 2019 19:08:44)
Included patches: 1-503, 505-680, 682-1283, 1365
Compiled by root@apple.com
```
Using the latest iTerm, no tmux.

**Comment by Rigellute** [comment]
It seems like that `vimrc` has a quirky way of handling third party themes.

Could you try following the instructions from this issue? https://github.com/amix/vimrc/issues/312

You might need to do something like this?
```sh
cd ~/.vim_runtime/sources_non_forked && git clone https://github.com/Rigellute/shades-of-purple.vim
```
And then in your custom config
```
colorscheme shades_of_purple
```

**Comment by Almoullim** [comment]
Since I already have the background set in iTerm. These lines fixed the issue with the background colors (Basically removes the background).
```vim
highlight Normal ctermbg=NONE
highlight nonText ctermbg=NONE
```
and 
```vim
highlight clear LineNr
```
to remove the background behind the line number, again, because it's already set through iTerm.

PS: Even without amix/vimrc configurations.

**Comment by Rigellute** [comment]
Great stuff. Thanks for posting your solution too 👍
