### ISSUE TITLE
Everything is yellow

### ISSUE THREAD

**Issue by yemeen** [Rigellute/shades-of-purple.vim#5]
<img width="829" alt="Screen Shot 2019-09-10 at 12 13 44 PM" src="https://user-images.githubusercontent.com/11223834/64631381-ff319100-d3c4-11e9-8d4b-cf231b138a50.png">

Could this be a macOS issue?

**Comment by Rigellute** [comment]
This is strange - I am running on macOS (with neovim within tmux) and having no issues.

Could you share your vim version, and `vimrc` please?

**Comment by yemeen** [comment]
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  9 2019 21:23:54)
macOS version
```

```
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
" A Vim Plugin for Lively Previewing LaTeX PDF Output
Plug 'xuhdev/vim-latex-live-preview', { 'for': 'tex' }
Plug 'lervag/vimtex'
Plug 'flazz/vim-colorschemes'
Plug 'Rigellute/shades-of-purple.vim'
Plug 'godlygeek/csapprox'
set termguicolors

"""" enable the theme
syntax on 
colorscheme default 
call plug#end()

let g:livepreview_previewer = 'open -a Preview'
let mapleader = " "
inoremap jk <ESC>
```
I have found disabling asci colors in terminal preferences will remove the yellow, but also most of the other colors in the theme.

**Comment by Rigellute** [comment]
One more question: which terminal emulator are you using? I recommend using [kitty](https://github.com/kovidgoyal/kitty). 

The default terminal emulator that comes with macOS does not support `truecolor` (which this theme makes use of). Read more about `truecolor` [here](https://gist.github.com/XVilka/8346728).

If you want to stick to the default terminal app do this instead
```diff
- set termguicolors

+ if (has("termguicolors"))
+   set termguicolors
+ endif
```

Let me know if that works for you, and I'll update the README

**Comment by yemeen** [comment]
I was using the default emulator, but now on both iTerm2 and Terminal I'm getting this scheme instead
<img width="682" alt="Screen Shot 2019-09-17 at 6 30 08 PM" src="https://user-images.githubusercontent.com/11223834/65084527-7c3aa880-d979-11e9-9eab-97e1fd09fdd2.png">

**Comment by yemeen** [comment]
Switched to MacVim and everything works as expected.

**Comment by Rigellute** [comment]
Thanks for your update
