### ISSUE TITLE
background doesn't work

### ISSUE THREAD

**Issue by tavoli** [Rigellute/shades-of-purple.vim#9]
![Captura de Tela 2019-12-31 às 04 34 29](https://user-images.githubusercontent.com/13285112/71613786-07d1f100-2b87-11ea-9cb2-da8f334b162b.png)

I love this theme, congratulations on your work!

I just installed but my background doesn't work properly ... I don't know why, I'm forgetting some configuration?

**Comment by Rigellute** [comment]
Hmm... could you tell me which terminal you are using?

**Comment by gapgag55** [comment]
Still same problem! I am using iterm2

**Comment by andrea-avanzi** [comment]
Hi, add the following to your .vimrc below colorscheme
`hi Normal guibg=NONE ctermbg=NONE`

[https://stackoverflow.com/a/37720708/13340533](https://stackoverflow.com/a/37720708/13340533)

**Comment by Rigellute** [comment]
Thanks for the solution @andrea-avanzi 👍 will close
